---
- name: Configuring Docker app
  hosts: all
  become: true
  tasks:

    - name: Stop previous version of container
      shell: docker stop myapp || true

    - name: Remove stopped container
      shell: docker rm -f myapp || true

    - name: Remove old docker image
      shell: docker rmi -f imgmyapp:v1 || true

    - name: Build docker image
      shell: docker build -t imgmyapp:v1 .

    - name: Run docker container
      shell: docker run -d -p 8089:8080 --name myapp imgmyapp:v1

    - name: Remove old WAR file from host
      file:
        path: ./webapp.war   # change to your WAR file path
        state: absent


